apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: {{ .Values.app }}-postgres
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        tier: postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Values.app }}-postgres-pvc

      containers:
        - image: postgres:15.2
          name: postgres
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db_name}}

            - name: POSTGRES_USER
              value: {{ .Values.db_user }}

            - name: POSTGRES_PASSWORD
              value: {{ .Values.db_password}}