apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app }}-postgres-pvc
  labels:
    app: {{ .Values.app }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi