apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: {{ .Values.app }}
    tier: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP