apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: {{ .Values.app }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app }}
    tier: backend
  ports:
    - port: 8000
      targetPort: 8000