# Generated by Django 4.2.7 on 2023-11-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
