name: Github Action Test Django Backend
on: [push]
jobs:
  Test-Django-Part:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r reminders_backend/requirements.txt
      - run: ./reminders_backends/pytest